modLoader = "javafml"
loaderVersion = "[2,)"
license = "MIT"

[[mods]]
modId = "obese_crops"
displayName = "Obese crops"
version = "${version}"
displayURL = ""
logoFile = "assets/icon.png"
authors = "macuguita"
description = '''Bigger crops, that bring a bountiful harvest!'''

[[mixins]]
config = "obese_crops.mixins.json"

[[dependencies.obese_crops]]
modId = "neoforge"
type = "required"
versionRange = "[21.1.181,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.obese_crops]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft}"

[[dependencies.obese_crops]]
modId = "macu_lib"
type = "required"
versionRange = "[2.0.0, ]"
